// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ComprimiseEmailsColumns holds the columns for the "comprimise_emails" table.
	ComprimiseEmailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Default: "unknown"},
	}
	// ComprimiseEmailsTable holds the schema information for the "comprimise_emails" table.
	ComprimiseEmailsTable = &schema.Table{
		Name:        "comprimise_emails",
		Columns:     ComprimiseEmailsColumns,
		PrimaryKey:  []*schema.Column{ComprimiseEmailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ComprimiseEmailsTable,
		UsersTable,
	}
)

func init() {
}
