// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hello/ent/comprimiseemail"
	"hello/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ComprimiseEmailDelete is the builder for deleting a ComprimiseEmail entity.
type ComprimiseEmailDelete struct {
	config
	hooks    []Hook
	mutation *ComprimiseEmailMutation
}

// Where adds a new predicate to the ComprimiseEmailDelete builder.
func (ced *ComprimiseEmailDelete) Where(ps ...predicate.ComprimiseEmail) *ComprimiseEmailDelete {
	ced.mutation.predicates = append(ced.mutation.predicates, ps...)
	return ced
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ced *ComprimiseEmailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ced.hooks) == 0 {
		affected, err = ced.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ComprimiseEmailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ced.mutation = mutation
			affected, err = ced.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ced.hooks) - 1; i >= 0; i-- {
			mut = ced.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ced.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ced *ComprimiseEmailDelete) ExecX(ctx context.Context) int {
	n, err := ced.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ced *ComprimiseEmailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: comprimiseemail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: comprimiseemail.FieldID,
			},
		},
	}
	if ps := ced.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ced.driver, _spec)
}

// ComprimiseEmailDeleteOne is the builder for deleting a single ComprimiseEmail entity.
type ComprimiseEmailDeleteOne struct {
	ced *ComprimiseEmailDelete
}

// Exec executes the deletion query.
func (cedo *ComprimiseEmailDeleteOne) Exec(ctx context.Context) error {
	n, err := cedo.ced.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{comprimiseemail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cedo *ComprimiseEmailDeleteOne) ExecX(ctx context.Context) {
	cedo.ced.ExecX(ctx)
}
