// Code generated by entc, DO NOT EDIT.

package comprimiseemail

const (
	// Label holds the string label denoting the comprimiseemail type in the database.
	Label = "comprimise_email"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// Table holds the table name of the comprimiseemail in the database.
	Table = "comprimise_emails"
)

// Columns holds all SQL columns for comprimiseemail fields.
var Columns = []string{
	FieldID,
	FieldEmail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEmail holds the default value on creation for the "Email" field.
	DefaultEmail string
)
