// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ComprimiseEmail is the predicate function for comprimiseemail builders.
type ComprimiseEmail func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
